### PR TITLE
✨Log In/Sign In

### LINKED ISSUE #28: ✨Log In/Sign In
## Summary
This should be the login or sign in page

### Basic example
Screenshot from 2023-08-18 20-22-38

### Acceptance criteria
should be pixel perfect to be accepted

### PR DESCRIPTION
**Pull request by VhugoJc**
Resolve #28 
### Introducing Log In Page with Reusable Components

Hi @mauricenyanja,

I'm excited to share the latest addition to our project: the Log In page! In this pull request, I've implemented the Log In functionality using the same set of reusable components that we've crafted earlier. By doing so, we're not only ensuring a consistent user experience but also keeping our codebase clean and efficient.

Should you decide to integrate the Log In page, you'll find that we're making the most of our **reusable components**, which significantly reduces code redundancy and maintenance efforts.

As always, your feedback is greatly appreciated. Feel free to explore the changes and let me know if you have any thoughts or questions.
Screenshot 2023-08-21 at 11 25 13

Cheers,
@VhugoJc

### CODE REVIEW

**Review by mauricenyanja — CHANGES_REQUESTED** [review]
use react-icons they are installed

**Comment by VhugoJc** [comment]
I created a Social Media Button (Component) for these buttons. Since I didn't find the exactly icons showed on the Figma Design, I had used Images. So, this is my approach using react-icons:

Screenshot 2023-08-22 at 14 11 34
Each Form is reusing the component with the onClick function in order to attach backend logic later.
Screenshot 2023-08-22 at 14 18 33
And this is how it looks:
Screenshot 2023-08-22 at 14 11 50
Screenshot 2023-08-22 at 14 12 05
Thank you for taking the time to review my pull request. Your feedback is highly valuable to me!!

**Review by mauricenyanja — APPROVED** [review]
Good job

**Comment by mauricenyanja** [comment]
Can u refractor ths sign up then it would be great

**Pull request merged**
